// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
    NODE_VERSION: "22";
}

// Custom additions
declare global {
    const EdgeRuntime: string | undefined;
}

export {};
